DROP DATABASE IF EXISTS TestingSystem;

CREATE DATABASE TestingSystem;

USE TestingSystem;

CREATE TABLE Department (
    DepartmentID INT NOT NULL AUTO_INCREMENT,
    DepartmentName VARCHAR(100) NOT NULL UNIQUE,
    PRIMARY KEY (DepartmentID)
);

CREATE TABLE Position(
    PositionID INT NOT NULL AUTO_INCREMENT,
    PositionName ENUM(
        "DEV",
        "TEST",
        "SCRUM MASTER",
        "PM"
    ),
    PRIMARY KEY (PositionID)
);

CREATE TABLE Account (
    AccountID INT NOT NULL AUTO_INCREMENT,
    Email VARCHAR(150) NOT NULL UNIQUE,
    Username VARCHAR(50) NOT NULL UNIQUE,
    FullName VARCHAR(100) NOT NULL,
    DepartmentID INT,
    PositionID INT,
    CreateDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (AccountID),
    FOREIGN KEY (DepartmentID) REFERENCES Department (DepartmentID) ON UPDATE CASCADE ON DELETE SET NULL,
    FOREIGN KEY (PositionID) REFERENCES Position(PositionID) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE `Group` (
    GroupID INT NOT NULL AUTO_INCREMENT,
    GroupName VARCHAR(100) NOT NULL,
    CreatorID INT NOT NULL,
    CreateDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (GroupID),
    FOREIGN KEY (CreatorID) REFERENCES Account (AccountID) ON DELETE RESTRICT
);

CREATE TABLE GroupAccount (
    GroupID INT NOT NULL,
    AccountID INT NOT NULL,
    JoinDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (GroupID, AccountID),
    FOREIGN KEY (GroupID) REFERENCES `Group` (GroupID) ON DELETE CASCADE,
    FOREIGN KEY (AccountID) REFERENCES Account (AccountID) ON DELETE CASCADE
);

CREATE TABLE TypeQuestion (
    TypeID INT NOT NULL AUTO_INCREMENT,
    TypeName VARCHAR(50) NOT NULL UNIQUE,
    PRIMARY KEY (TypeID)
);

CREATE TABLE CategoryQuestion (
    CategoryID INT NOT NULL AUTO_INCREMENT,
    CategoryName VARCHAR(100) NOT NULL UNIQUE,
    PRIMARY KEY (CategoryID)
);

CREATE TABLE Question (
    QuestionID INT NOT NULL AUTO_INCREMENT,
    Content TEXT NOT NULL,
    CategoryID INT NOT NULL,
    TypeID INT NOT NULL,
    CreatorID INT NOT NULL,
    CreateDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (QuestionID),
    FOREIGN KEY (CategoryID) REFERENCES CategoryQuestion (CategoryID) ON DELETE RESTRICT,
    FOREIGN KEY (TypeID) REFERENCES TypeQuestion (TypeID) ON DELETE RESTRICT,
    FOREIGN KEY (CreatorID) REFERENCES Account (AccountID) ON DELETE RESTRICT
);

CREATE TABLE Answer (
    AnswerID INT NOT NULL AUTO_INCREMENT,
    Content TEXT NOT NULL,
    QuestionID INT NOT NULL,
    isCorrect TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (AnswerID),
    FOREIGN KEY (QuestionID) REFERENCES Question (QuestionID) ON DELETE CASCADE
);

CREATE TABLE Exam (
    ExamID INT NOT NULL AUTO_INCREMENT,
    Code VARCHAR(50) NOT NULL,
    Title VARCHAR(200) NOT NULL,
    CategoryID INT NOT NULL,
    Duration INT NOT NULL,
    CreatorID INT NOT NULL,
    CreateDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ExamID),
    UNIQUE KEY uq_exam_code (Code),
    FOREIGN KEY (CategoryID) REFERENCES CategoryQuestion (CategoryID) ON DELETE RESTRICT,
    FOREIGN KEY (CreatorID) REFERENCES Account (AccountID) ON DELETE RESTRICT,
    CONSTRAINT chk_duration CHECK (Duration > 0)
);

CREATE TABLE ExamQuestion (
    ExamID INT NOT NULL,
    QuestionID INT NOT NULL,
    PRIMARY KEY (ExamID, QuestionID),
    FOREIGN KEY (ExamID) REFERENCES Exam (ExamID) ON DELETE CASCADE,
    FOREIGN KEY (QuestionID) REFERENCES Question (QuestionID) ON DELETE RESTRICT
);