CREATE DATABASE IF NOT EXISTS LibraryDB;

USE LibraryDB;

CREATE TABLE Author (
    AuthorID INT AUTO_INCREMENT PRIMARY KEY,
    FullName VARCHAR(50) NOT NULL,
    Nationality VARCHAR(50) NOT NULL,
    BirthDate DATE
);

CREATE TABLE Book (
    BookID INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(100) NOT NULL,
    AuthorID INT NOT NULL,
    PublishedYear YEAR,
    Price DECIMAL(10, 2) NOT NULL CHECK (Price >= 0),
    Stock INT UNSIGNED DEFAULT 0,
    FOREIGN KEY (AuthorID) REFERENCES Author (AuthorID)
);

CREATE TABLE Member (
    MemberID INT AUTO_INCREMENT PRIMARY KEY,
    FullName VARCHAR(50) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    Phone VARCHAR(20) UNIQUE,
    RegisterDate DATETIME DEFAULT CURRENT_TIMESTAMP
);